### ISSUE TITLE
"maker only" mode for buysell

### ISSUE THREAD

**Issue by jimdanz** [interstellar/kelp#34]
## Desired Behavior
The bot should have a mode where it tries to only make orders that do not cross any existing orders (maker only orders).

## Impact
This can help you avoid unnecessary wash trades if someone else is also market-making but your price feeds or preferences are causing you to place slightly different orders.

## Feature Suggestion
Without the DEX protocol itself supporting maker-only orders, anything done in the bot will be a best effort.  However, I believe that the basic flow is simply: each time re-evaluating orders to place:
* first load all orders for the asset pair from the DEX
* check if the order you'd be placing will cross with an existing order.  If it would, do not place it.

## References
Bots aimed at centralized exchanges will generally have this feature because centralized exchanges usually price maker vs. taker orders quite differently.

Example: https://github.com/DeviaVir/zenbot#strategies

## Additional context
I believe this should be a flag/parameter for buysell.  There's an argument that it could be its own strategy, but I think it's better as a parameter because it might apply to various different strategies (could apply to sell as well, maybe even to balanced).

## Specification
(updated by @nikhilsaraf: flag should be optional and in the strategy config file but execution by the framework, augment the strategy interface to support this. This should be handled by either the framework or the exchange implementation but the framework can do the threading of the flag. For the SDEX implementation we can filter out orders by querying the orderbook to find and delete the intersection between existing orderbook and orders we want to create)

**Comment by Reidmcc** [comment]
The behavior you describe of not matching any existing orders is already accomplished to the extent possible by the staticSpreadLevelProvider; the bot's order levels are offset from the center price based on the config settings, up and down for sell and buy respectively. By definition, there are no buy offers higher than the center price and no sell offers lower than the center price, hence checking the individual offers is not necessary.

What it does not do is prevent your order from filling another order that arrives between when the bot checks the center price and when the bot's orders are placed. Another check of the orderbook would not help; another trader's order could still arrive between your book check and your order's arrival. Which is the main purpose of a maker-only order on a centralized exchange. This condition is not supported by the Stellar protocol itself, see the [market guide](https://www.stellar.org/developers/guides/concepts/exchange.html).

**Comment by nikhilsaraf** [comment]
@jimdanz this is a good feature request. We can do this at the framework level to support all strategies and take this input as a command line param to the bot's `trade` command.

Before placing any orders (submitting to the DEX) we can "delete" any orders (manageOffer operations, really) that will cross the existing orderbook. This can be done by querying the orderbook to find the intersection between the existing orders and the orders you intend on placing.

Is the proposed approach a viable solution for you?

-----

@Reidmcc I think the center price in the staticSpreadLevelProvider would be taken from a priceFeed, not from the DEX itself, so it is likely to differ from the current state of the DEX's orderbook.

**Comment by nikhilsaraf** [comment]
@Reidmcc `GetPrice()` does not pull from the DEX :)
it pulls from data sources **outside** the DEX (such as coinmarketcap, kraken, binance, etc.)

**Comment by Reidmcc** [comment]
@nikhilsaraf Ah, misunderstanding on my part. Thanks.

**Comment by nikhilsaraf** [comment]
yes, I think we can make it work by keeping it at the strategy config level -- will have to augment the interface for the strategy a little but I think it should be possible. Updated your original comment to include this in the specification section.

this is something that I'll try to include in the November release since I have a couple of pressing changes I'm currently working on.

**Comment by nikhilsaraf** [comment]
blocked on #97 which introduces the `GetOrderBook` API method on sdex.go

**Comment by nikhilsaraf** [comment]
@jimdanz fyi, you can use this feature now once you check out the master branch. 
just add `SUBMIT_MODE="maker_only"` in the trader.cfg file.

See the [sample_trader.cfg](https://github.com/interstellar/kelp/blob/master/examples/configs/trader/sample_trader.cfg#L24) file as an example. let me know if you run into any issues.

**Comment by jimdanz** [comment]
Awesome!!! 💯 
Very stoked to give this a try.  Thanks @nikhilsaraf !
