### ISSUE TITLE
Private keys should be able to be specified in environment variables

### ISSUE THREAD

**Issue by skirsch** [interstellar/kelp#80]
// see sample feature request here: https://github.com/interstellar/kelp/issues/2

## Desired Behavior
// A succinct description of **what you are trying to achieve** that is not currently supported.
// This can be a request for a new plugin too (strategy, price feed, exchange).
// If your feature request is related to a problem with an existing feature then please _submit a bug report_ instead.
// If this feature does not exist anywhere else then please restrict details to the _Specification_ section below.

i want to spec private keys in environment variables and have script refer to that for specifying. Otherwise this is a disaster to have private keys in github.

## Impact
// A succinct description of **why you want the _desired behavior_** specified above.

trading and source secret seed should allow me to reference an environment variable name, rather than just a string.

## Feature Suggestion
// A succinct description of **how you want to achieve the desired behavior**.
// If you have looked at the code and know exactly what code changes are needed then please _consider submitting a pull request_ instead.
// If this feature does not exist anywhere else then please restrict any details to the _Specification_ section below.
trading and source secret seed should allow me to reference an environment variable name, rather than just a string

**Comment by nikhilsaraf** [comment]
closing as discussed @skirsch
