### ISSUE TITLE
invalid sequence number errors (in latest release) when trading multiple symbols

### ISSUE THREAD

**Issue by skirsch** [interstellar/kelp#81]
// see a sample bug report here: https://github.com/interstellar/kelp/issues/1

## Describe the bug
// A succinct description of the buggy behavior.
// This section includes **what** the bot is doing and **why** you think it is incorrect.

I trade 4 different markets using the same account number to place the trades. So since you have 4 different kelps running you are going to get an invalid sequence number error.  

## Expected behavior
// A succinct description of **what you expected to happen**.

When kelp wakes up, and is ready to do it's thing, it should ideally re-fetch the sequence number. I guess this is a performance optimization?

## Frequency
// **How often** does this happen?
//     Unpredictable = it's hard to predict when it will happen
//     Sometimes = it happens every now and then but there's no pattern to it
//     Always = it always happens consistently at the same point

all the time

## Steps To Reproduce
// A concise description of the **steps to reproduce the buggy behavior** along with screenshots wherever applicable:

run >1 kelp instance with the same SOURCE_SECRET_SEED

## Possible Solution
// Optional, suggest a fix.

This bug can be avoided by using unique SOURCE_SECRET_SEED for each kelp instance.

You cannot stagger the start time so no overlap since kelp doesn't fetch the seq number each time.

## Your Environment
// Run `kelp version` to get the version and build information and paste it here
//   version: v1.0.0-rc1
//   git hash: 1bcc4e9fa4012867a549472dbdf61cb008041305
//   build date: 20180813T013016Z
//   GOOS: linux
//   GOARCH: amd64

n/a

## Context
// A succinct description of how has this bug has **affected you** or prevented you from accomplishing what you wanted.

n/a
## Attachments
// Attach any relevant configuration files, logs, tx hashes, etc. here.

**Comment by nikhilsaraf** [comment]
If you have 4 bots you want to run out of the same account, you should configure them like so:
```
Account1:
Trading Account: Key0
Source Account: Key1

Account2:
Trading Account: Key0
Source Account: Key2

Account3:
Trading Account: Key0
Source Account: Key3

Account4:
Trading Account: Key0
Source Account: Key4
```

This way you only need N+1 stellar keys to trade on N markets by leveraging the source secret seed field in the trader.cfg of each bot. The source_secret_seed helps to separate out the sequence number coordination and network fee payments when using more than 1 bot on a trading account.

closing this, feel free to reopen if you think this is still unresolved.
