### ISSUE TITLE
Error: Failed to load endpoint Kelp 1.3.0

### ISSUE THREAD

**Issue by Pedity-Luffy** [interstellar/kelp#93]
// see a sample bug report here: https://github.com/interstellar/kelp/issues/1

## Describe the bug
// A succinct description of the buggy behavior.
Kelp 1.3.0 is throwing this error : failed to load endpoint: Get https://horizon.stellar.org/trades/?base_asset_t
ype=native&counter_asset_code=PEDI&counter_asset_issuer=GBVUDZLMHTLMZANLZB6P4S4RYF52MVWTYVYXTQ2EJBPBX4DZI2SDOLLY
&counter_asset_type=c
I have added the logs in the log section below.

// This section includes **what** the bot is doing and **why** you think it is incorrect.

The bot is unable to load endpoint and probably causing the bot to exit.

## Expected behavior
// A succinct description of **what you expected to happen**.

I think the correct behavior in this situation is for the bot should not exit and check correct endpoint. It might be possible that the endpoint URL is correct and the bot is having some extra character in the URL which is causing invalid endpoint.

## Frequency
// **How often** does this happen?
//     Unpredictable = it's hard to predict when it will happen
//     Sometimes = it happens every now and then but there's no pattern to it
//     Always = it always happens consistently at the same point

The frequency is: Unpredictable, we added this kelp bot 1.3.0 yesterday and encountered this issue.

## Steps To Reproduce
It's quite unpredictable but let me know if you need the balanced strategy conf that we are using.

Here are the steps to reproduce the issue (see attachments in section below):
1. Set up your configuration file with these parameters: ...
2. Start the bot using this command: ...
...

## Possible Solution
I think it is best to check all the endpoints in new kelp version, it might be latest changes in horizon have caused the crash.

This bug can be fixed by ...

## Your Environment
// Run `kelp version` to get the version and build information and paste it here
  version: master:v1.3.0
  git branch: master
  git hash: e19784fc9cdb113d5b51c8f421c8ab2d49752dc0
  build date: 20190111T004556Z
  GOOS: linux
  GOARCH: amd64

## Context
// A succinct description of how has this bug has **affected you** or prevented you from accomplishing what you wanted.

I am unable to run the bot because of this bug and it the code exits as it the bot make panic exit.

## Attachments
// Attach any relevant configuration files, logs, tx hashes, etc. here.
Logs : 019/01/15 00:03:30 problem encountered while running the fill tracker: error when fetching trades: error while 
fetching trades in SDEX (cursor=): failed to load endpoint: Get https://horizon.stellar.org/trades/?base_asset_t
ype=native&counter_asset_code=PEDI&counter_asset_issuer=GBVUDZLMHTLMZANLZB6P4S4RYF52MVWTYVYXTQ2EJBPBX4DZI2SDOLLY
&counter_asset_type=credit_alphanum4&cursor=&limit=200&offer_id=0&order=asc&resolution=300000: read tcp 10.142.0
.2:38296->104.20.59.10:443: read: connection reset by peer
2019/01/15 00:03:30 
2019/01/15 00:03:30 deleting all offers and then exiting...
2019/01/15 00:03:30 created 8 operations to delete offers
2019/01/15 00:03:30 tx XDR: 2019/01/15 00:03:30 submitting tx XDR to network (async)
2019/01/15 00:03:30 sleeping for 10 seconds until our deletion is confirmed and we exit...
2019/01/15 00:03:40 sleeping for 10 seconds until our deletion is confirmed and we exit...
2019/01/15 00:03:43 (async) tx confirmation hash: f7d6be9bdef44a516761fe24bba8ead9f45f4f1d695141e034ebf8e394a853
0b
2019/01/15 00:03:43 ...deleted all offers, exiting

**Comment by Pedity-Luffy** [comment]
For now, we are using kelp version 1.1.2 (It has been working for nearly a long time without any crash) as this is crashing unpredictably.

**Comment by nikhilsaraf** [comment]
@Pedity-Luffy  I tried the endpoint you suggested and it works.

The error you received seems to arise from network connection issues (`"read: connection reset by peer"`) which is a transient issue.

In order to accommodate such transient issues you should set your `DELETE_CYCLES_THRESHOLD` (available since v1.2.0) to be > 0 to tolerate a few cycles with transient errors. It would be useful to experiment with different values for this parameter to see what works best for you. You could alternatively contact your ISP to resolve any network issues you are facing.

Please let me know if this fixes it for you.

**Comment by nikhilsaraf** [comment]
@Pedity-Luffy let me know how it works for you when you try with `DELETE_CYCLES_THRESHOLD=2`

If that doesn't solve the problem for you then you can also try and turn off trade tracking (unless you are using the balanced strategy) by setting `FILL_TRACKER_SLEEP_MILLIS=0`, or by setting that value to be a larger number for slower trade tracking queries.

**Comment by Pedity-Luffy** [comment]
@nikhilsaraf You were right, the `DELETE_CYCLE_THRESHOLD` did fix this issue but a new issue came. It ran pretty well for a day so I am happy but hope you can suggest the issue here 
```
2019/01/17 18:44:02 problem encountered while running the fill tracker: error when fetching trades: error while 
fetching trades in SDEX (cursor=): error decoding horizon.Problem: invalid character '<' looking for beginning o
f value
2019/01/17 18:44:02 
2019/01/17 18:44:02 deleting all offers and then exiting...
2019/01/17 18:44:03 created 13 operations to delete offers
```

**Comment by nikhilsaraf** [comment]
ok this is an interesting issue -- the fill tracker currently does not accommodate errors and exits immediately, maybe we can let the fill tracker accommodate N errors (defined separately in config file) so that we exit only if it fails N times (this is the equivalent of `DELETE_CYCLES_THRESHOLD` but for the fill tracker). Filed an issue to address this here: https://github.com/interstellar/kelp/issues/96 

closing this issue for now, please use the new issue to discuss this solution, or feel free to reopen this issue if it's still failing when you set `FILL_TRACKER_SLEEP_MILLIS=0`
